spring:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:h2:file:C:/Users/AllWare/Desktop/Todo-app_clean/todo-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE'
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TodoApp'
  resource: 'todo-spring-client'
  public-client: true